- name: setup isolcpus boot param (ec2)
  lineinfile:
    dest: /etc/default/grub.d/50-cloudimg-settings.cfg
    regexp: '(^GRUB_CMDLINE_LINUX_DEFAULT="(\s*(?!isolcpus)[\w=/\-\.]+)*\s*)"\s*$'
    line: '\1 isolcpus={{ system_cpus }}"'
    backrefs: true
    state: present
    backup: true
  register: grubfile
  when: ({{ 'vagrant' != ansible_ssh_user }} and {{ system_cpus is defined }} and {{ isolcpus is defined }} and {{ isolcpus == 'true' }} and {{ ansible_ec2_instance_id is defined }})

- name: remove isolcpus boot param if it exists (ec2)
  lineinfile:
    dest: /etc/default/grub.d/50-cloudimg-settings.cfg
    regexp: '(^GRUB_CMDLINE_LINUX_DEFAULT=".*) isolcpus.*"$'
    line: '\1"'
    backrefs: true
    state: present
    backup: true
  register: grubfile2
  when: ({{ 'vagrant' != ansible_ssh_user }} and ({{ isolcpus is not defined }} or ({{ isolcpus is defined }} and {{ isolcpus != 'true' }})) and {{ ansible_ec2_instance_id is defined }})

- name: update grub
  command: update-grub
  when: ('vagrant' != '{{ ansible_ssh_user }}' and (grubfile|changed or grubfile2|changed) and {{ ansible_ec2_instance_id is defined }})

- name: setup isolcpus boot param (not ec2)
  lineinfile:
    dest: /boot/grub/grub.cfg
    regexp: '^( +linux.+/boot/vmlinuz)( isolcpus={{ system_cpus }} )?(.+(?!single).+\s*)$'
    line: '\1 isolcpus={{ system_cpus }} \3'
    backrefs: true
    state: present
    backup: true
  register: grubfile3
  when: ({{ 'vagrant' != ansible_ssh_user }} and {{ system_cpus is defined }} and {{ isolcpus is defined }} and {{ isolcpus == 'true' }} and {{ ansible_ec2_instance_id is not defined }})

- name: remove isolcpus boot param if it exists (not ec2)
  lineinfile:
    dest: /boot/grub/grub.cfg
    regexp: '(^ +linux.*) isolcpus=\d+ +(.*)$'
    line: '\1 \2'
    backrefs: true
    state: present
    backup: true
  register: grubfile4
  when: ({{ 'vagrant' != ansible_ssh_user }} and ({{ isolcpus is not defined }} or ({{ isolcpus is defined }} and {{ isolcpus != 'true' }})) and {{ ansible_ec2_instance_id is not defined }})


- name: reboot to apply isolcpus boot param
  shell: sleep 2 && /sbin/shutdown -r now "Apply isolcpus boot param"
  when: ('vagrant' != '{{ ansible_ssh_user }}' and (grubfile|changed or grubfile2|changed or grubfile3|changed or grubfile4|changed))
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=600 port=22
  become: false
  when: ('vagrant' != '{{ ansible_ssh_user }}' and (grubfile|changed or grubfile2|changed or grubfile3|changed or grubfile4|changed))

- name: Get groups for ssh user
  command: groups {{ ansible_ssh_user }}
  register: my_groups

- name: Add sendence group
  group: name=sendence state=present gid=1111

- name: Add sendence user
  user:
    name: sendence
    uid: 1111
    group: sendence
    shell: /bin/bash
    groups: "{{ my_groups.stdout.split(':')[1] | replace(' ', ',') }}"

- name: Copy ssh keys for sendence user
  command: creates=/home/sendence/.ssh cp -rf /home/{{ ansible_user_id }}/.ssh /home/sendence/
  when: (ansible_ssh_user != "root")

- name: Copy ssh keys for sendence user
  command: creates=/home/sendence/.ssh cp -rf /root/.ssh /home/sendence/
  when: (ansible_ssh_user == "root")

- name: Change ownership ssh keys for sendence user
  file: path=/home/sendence/.ssh owner=sendence group=sendence recurse=yes state=directory

- name: allow sendence user to sudo without password
  lineinfile:
    dest: /etc/sudoers
    regexp: '^sendence'
    line: 'sendence ALL=(ALL) NOPASSWD:ALL'
    state: present
    backup: true

- name: Install common packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
   - curl
   - libpcap0.8
   - python-boto
   - python-pip
   - python3
   - python3-pip
   - python3-numpy
   - less
   - dnsutils
   - net-tools
   - vim
   - wget
   - jq
   - sysstat
   - htop
   - numactl
   - cpuset
   - trace-cmd
   - stress-ng

- name: Install common packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
   - linux-tools-{{ ansible_kernel }}
  ignore_errors: yes

- name: Install python3 click
  pip: name=click executable=pip3

- name: Check if ptpd is installed
  stat: path=/usr/sbin/ptpd
  register: ptpd

- name: Get ptpd deb for armhf
  get_url:
     url: https://s3.amazonaws.com/sendence-dev/installers/ptpd/ptpd_2.3.2-master-1_armhf.deb
     dest: /tmp/ptpd_2.3.2-master-1_armhf.deb
     mode: 0755
  register: get_url_result
  until: get_url_result | succeeded
  retries: 5
  delay: 5
  when: ('arm' == '{{ ansible_architecture[0:3] }}') and (not ptpd.stat.exists)

- name: Install ptp for armhf
  apt: deb=/tmp/ptpd_2.3.2-master-1_armhf.deb
  when: ('arm' == '{{ ansible_architecture[0:3] }}') and (not ptpd.stat.exists)

- name: Get ptpd deb for x86_64
  get_url:
     url: https://s3.amazonaws.com/sendence-dev/installers/ptpd/ptpd_2.3.2-master-1_amd64.deb
     dest: /tmp/ptpd_2.3.2-master-1_amd64.deb
     mode: 0755
  register: get_url_result
  until: get_url_result | succeeded
  retries: 5
  delay: 5
  when: (ansible_architecture == "x86_64") and (not ptpd.stat.exists)

- name: Install ptp for x86_64
  apt: deb=/tmp/ptpd_2.3.2-master-1_amd64.deb
  when: (ansible_architecture == "x86_64") and (not ptpd.stat.exists)

- name: add llvm apt repo key
  apt_key:
    url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    state: present
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: add llvm apt repo
  apt_repository:
    repo: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.8 main'
    state: present
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: add llvm src apt repo
  apt_repository:
    repo: 'deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.8 main'
    state: present
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: Install dev packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
   - automake
   - autotools-dev
   - build-essential
   - file
   - git
   - libicu-dev
   - libncurses5-dev
   - libpcre3
   - libssl-dev
   - libxml2-dev
   - zlib1g-dev
   - software-properties-common
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: Download pcre2
  get_url:
    url: "http://downloads.sourceforge.net/project/pcre/pcre2/10.21/pcre2-10.21.tar.bz2"
    dest: "/tmp/pcre2-src.tbz2"
  register: get_url_result
  until: get_url_result | succeeded
  retries: 5
  delay: 5
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: Expand pcre2 archive
  unarchive:
    src: "/tmp/pcre2-src.tbz2"
    dest: "/tmp"
    creates: "/tmp/pcre2-10.21/README"
    copy: no
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: configure pcre2
  command: >
    ./configure prefix=/usr
    chdir=/tmp/pcre2-10.21
    creates=/tmp/pcre2-10.21/libtool
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: build pcre2
  command: >
    make
    chdir=/tmp/pcre2-10.21
    creates=/tmp/pcre2-10.21/pcre2test
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: install pcre2
  command: >
    make install
    chdir=/tmp/pcre2-10.21
    creates=/usr/bin/pcre2test
  when: ({{ install_devtools is defined }} and {{ install_devtools == 'true' }})

- name: List ponyc custom C libs from S3
  s3:
    mode=list
    bucket=sendence-dev
    prefix=ponyc_external_dependencies/
  delegate_to: 127.0.0.1
  become: no
  register: s3_bucket_items

- name: Filter list of ponyc custom C libs (amd64)
  set_fact:
    custom_libs: "{{ s3_bucket_items.s3_keys | select('search', '/amd64') | list }}"
  when: (ansible_architecture == "x86_64")

- name: Filter list of ponyc custom C libs (armhf)
  set_fact:
    custom_libs: "{{ s3_bucket_items.s3_keys | select('search', '/armhf') | list }}"
  when: ('arm' == '{{ ansible_architecture[0:3] }}')

- name: download ponyc custom C libs from S3
  get_url:
     url: https://s3.amazonaws.com/sendence-dev/{{ item }}
     dest: /tmp/{{ item | basename }}
     mode: 0755
  with_items: custom_libs
  register: get_url_result
  until: get_url_result | succeeded
  retries: 5
  delay: 5

- name: unarchive ponyc custom C libs
  unarchive:
    src=/tmp/{{ item | basename }}
    dest=/usr/
    copy=no
  with_items: custom_libs

- name: apply kernel tweaks
  script: kerneltweaks.sh > /kerneltweaks.out
  when: ('vagrant' != '{{ ansible_ssh_user }}')

- name: create cpu shield
  script: create_cpu_shield.sh {{ system_cpus if system_cpus is defined else "" }} > /create_cpu_shield.out
  when: ('vagrant' != '{{ ansible_ssh_user }}')

